# -*- coding: utf-8 -*-
"""Limpeza_de_Dados_de_DataClean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lo1jmTX8BUZsgFomIAXyQYzzK0IVF9rj

# Bibliotecas
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import zscore

"""# Coleta de Dados"""

df = pd.read_csv('/content/dados_clientes.csv')

df.head()

df.info()

df.describe()

"""# Observação dos Dados"""

df.isnull().sum()

df.duplicated().sum()

"""### **Idade**"""

df[['idade']].hist(bins = 10, figsize=(15,5))
plt.show()

# Dois valores faltando, nenhum outlier aparente, média e mediana próximos, com desvio padrão aceitável.

sns.boxplot(x = df['idade'])
plt.show()

"""### Renda Anual"""

df[['renda_anual']].hist(bins = 50, figsize=(15,5))
plt.show()

# Um valor faltando, dois possíveis outliers.

sns.boxplot(x = df['renda_anual'])
plt.show()

"""### Valor da Compra"""

df[['valor_compra']].hist(bins = 50, figsize=(15,5))
plt.show()

# Dois valores faltando, dois possíveis outliers.

sns.boxplot(x = df['valor_compra'])
plt.show()

"""# Tratando dados Ausentes"""

df_limpo = df.copy()

df_limpo["idade"] = df_limpo["idade"].fillna(df_limpo["idade"].median())
df_limpo["renda_anual"] = df_limpo["renda_anual"].fillna(df_limpo["renda_anual"].median())
df_limpo["valor_compra"] = df_limpo["valor_compra"].fillna(df_limpo["valor_compra"].median())

# Completando valores ausentes com a mediana.
# Não removi por se tratar de uma porcentagem muito alta.
# Optei em subistituir pela mediana, para que tenha menor influência de possíveis outliers e ainda possa ser usado.

df_limpo.head()

df_limpo.info()

df_limpo.describe()

"""# Tratando Duplicatas"""

df_limpo.duplicated().sum()

# Aparentemente não tem duplicata, mas...
# O ID único não é único, a ideia é criar um ID único de fato.
# Utilizando nome + idade + região + renda_aunal + genero.

#O campo id_cliente apresenta inconsistência e não pode ser considerado identificador único de cliente.
# Vou criar um novo identificador único com base nos nomes, conferindo a idade e a região.
# (pois mesmo se o nome for igual, se a idade ou a região forem diferentes, é uma pessoa diferente)
df_limpo.groupby(["nome", "idade", "regiao", "genero", "renda_anual"]).size()

df_modelo = df_limpo.copy()
# Criando um novo DF para adicionar uma nova ID única para clientes.

clientes = (
    df_modelo[
        ["nome", "idade", "genero", "renda_anual", "regiao"]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)
# O novo ID será representado pelo nome + idade + genero + renda anual + regiao; se pelo menos um for diferente, é um novo cliente.

clientes["id_cliente_novo"] = range(1, len(clientes) + 1)
# Criar ID único para clientes

# Conectar vendas com clientes
df_modelo = df_modelo.merge(
    clientes,
    on=["nome", "idade", "genero", "renda_anual", "regiao"],
    how="left"
)

df_modelo

"""# Analizando Outliers"""

df_outliers = df_modelo.copy()

"""### Idade"""

sns.boxplot(x = df_outliers['idade'])
plt.show()

# Aparentemente, valores acima de 60 são outliers, mas ao usar o zscore, eles não aparecem como outliers.
# Por se tratar de idade, vou manter por causa do zscore.

zscore(df_outliers['idade'])

"""### Renda"""

sns.boxplot(x = df_outliers['renda_anual'])
plt.show()

# É visível que dois valores estão muito acima dos outros.

zscore(df_outliers['renda_anual'])

# Mesmo usando o zscore temos um 4.3 e um 2.4.
# Um claramente outlier e outro muito próximo disso.
# Optei por remover devido ao IQR.

"""### Valor da Compra"""

sns.boxplot(x = df_outliers['valor_compra'])
plt.show()

# É visível dois valores muito acima dos outros.

zscore(df_outliers['valor_compra'])

# Mesmo usando o zscore temos um 4.1 e um 2.8
# Um claramente outlier e outro muito próximo disso
# Optei por remover devido ao IQR

"""### Removendo Renda e valor compra"""

# removendo renda
Q1 = df_outliers["renda_anual"].quantile(0.25)
Q3 = df_outliers["renda_anual"].quantile(0.75)
IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

df_outliers = df_outliers[
    (df_outliers["renda_anual"] >= limite_inferior) &
    (df_outliers["renda_anual"] <= limite_superior)
]

# removendo Venda
Q1 = df_outliers["valor_compra"].quantile(0.25)
Q3 = df_outliers["valor_compra"].quantile(0.75)
IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

df_outliers = df_outliers[
    (df_outliers["valor_compra"] >= limite_inferior) &
    (df_outliers["valor_compra"] <= limite_superior)
]

df_outliers.describe()

df_outliers.info()

"""# Encoding"""

df_encoding = df_outliers.copy()

"""### genero"""

df_encoding = pd.get_dummies(df_encoding, columns=['genero'])
df_encoding

"""### Categoria de Produto"""

df_encoding['categoria_produto_label'] = df_encoding['categoria_produto'].astype('category').cat.codes
df_encoding

#Beleza -> 0
#Casa -> 1
#Eletrôniocos -> 2
#Esporte -> 3
#Moda -> 4

"""### Região"""

df_encoding['regiao_label'] = df_encoding['regiao'].astype('category').cat.codes
df_encoding

#Centro-Oeste -> 0
#Nordeste-> 1
#Norte -> 2
#Sudeste-> 3
#Sul -> 4

"""# Arrumando a data"""

df_data = df_encoding.copy()

df_data["data_compra_corrigido"] = pd.to_datetime(df_data["data_compra"], errors="coerce")

# Padronizar os separadores antes
df_data["data_compra"] = (
    df_data["data_compra"]
    .astype(str)
    .str.strip()
    .str.replace("/", "-", regex=False)
)

# converter e criar uma nova área
df_data["data_compra_corrigido"] = pd.to_datetime(df_data["data_compra"], errors="coerce")

df_data.info()

# Criando novas 3 tabelas: ano, mês, dia da semana.
df_data["ano"] = df_data["data_compra_corrigido"].dt.year
df_data["mes"] = df_data["data_compra_corrigido"].dt.month
df_data["dia_semana"] = df_data["data_compra_corrigido"].dt.dayofweek

df_data[["data_compra", "data_compra_corrigido", "ano", "mes", "dia_semana"]]

"""# Tabela Final"""

df_final = df_data.copy()

df_final