# -*- coding: utf-8 -*-
"""Analise de Delivery de Refeicoes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kp1xetZNd0PFlUruDn7WB6cwrQ0v3baq
"""

# 1. Importações
import pandas as pd
import numpy as np

# 2. Carregamento dos Dados
df_pedidos = pd.read_csv('/content/pedidos.csv')

# 3. EDA
# Explore os dados
df_pedidos.head()

df_pedidos.tail()

df_pedidos.info()

df_pedidos.describe()

# 4. Feature Engineering
# Crie novas colunas
df_pedidos['Receita_Item'] = df_pedidos['Quantidade'] * df_pedidos['Preco_Unitario']
df_pedidos.head()

# 5. Tratamento de Dados
# Lide com valores ausentes
df_pedidos.isna().sum()

df_pedidos_preenchido = df_pedidos.copy()
media_qtd = df_pedidos_preenchido['Quantidade'].mean()
df_pedidos_preenchido['Quantidade'].fillna(media_qtd, inplace=True)
df_pedidos_preenchido.isna().sum()

df_pedidos_limpo = df_pedidos_preenchido.dropna(subset=['Preco_Unitario'])
df_pedidos_limpo.info()

# 6. Agregações
# Analise por item
pedidos_por_itens = df_pedidos_limpo.groupby('Item').agg(
    Quantidade_Total = ('Quantidade', 'sum'),
    Receita_Total = ('Receita_Item', 'sum')
).reset_index()
print(pedidos_por_itens)

itens_mais_pedidos = pedidos_por_itens.sort_values(by='Quantidade_Total', ascending=False).iloc[0:5]
print(itens_mais_pedidos)

itens_maior_receita = pedidos_por_itens.sort_values(by='Receita_Total', ascending=False).iloc[0:5]
print(itens_maior_receita)

# 7. Análise Temporal
# Analise por período
df_pedidos_limpo['Data'] = pd.to_datetime(df_pedidos_limpo['Data'])
df_pedidos_limpo.info()

df_pedidos_limpo['Mes_Pedido'] = df_pedidos_limpo['Data'].dt.month
df_pedidos_limpo.head()

pedidos_por_mes = df_pedidos_limpo.groupby('Mes_Pedido')['Receita_Item'].sum().reset_index()
print(pedidos_por_mes)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Mes_Pedido']
  ys = series['Receita_Item']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_7.sort_values('Mes_Pedido', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Mes_Pedido')
_ = plt.ylabel('Receita_Item')

df_cardapio = pd.read_csv('/content/cardapio.csv')

# 8. Merge
# Integre com cardápio
df_merge = pd.merge(df_pedidos, df_cardapio, on='Item', how='left')
print(df_merge)

receita_por_categoria = df_merge.groupby('Categoria').agg(Receita_Total = ('Receita_Item', 'sum')).reset_index()
print(receita_por_categoria)

categoria_maior_receita = receita_por_categoria.sort_values(by='Receita_Total', ascending=False).iloc[0]
print(categoria_maior_receita)

# 9. Filtros
# Aplique filtros específicos
df_query = df_merge.query('Categoria == "Salgados" and Quantidade > 10')
print(df_query)

# 10. KPIs
# Calcule indicadores
receita_total_gerada = df_merge['Receita_Item'].sum()
print(receita_total_gerada)

total_itens_vendidos = df_merge['Quantidade'].sum()
print(total_itens_vendidos)

ticket_medio = receita_total_gerada / total_itens_vendidos
print(ticket_medio)

