# -*- coding: utf-8 -*-
"""EDA_Tech_Store

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gw5XBYb8dSLfP49ffg6Jg_yp9c70-wMo
"""

import pandas as pd
import sqlite3
import matplotlib.pyplot as plt

# Carregar os dados
df_vendas = pd.read_csv('/content/vendas.csv')

# Mostrar as 5 primeiras linhas do dataset.
df_vendas.head()

# Exibir o número total de registros (linhas).
print("Total de registros:", df_vendas.shape[0])

# Calcular a receita total (coluna quantidade multiplicada pela coluna preco_unitario).
df_vendas['receita'] = df_vendas['quantidade'] * df_vendas['preco_unitario']
receita_total = df_vendas['receita'].sum()
print("Receita total:", receita_total)

# Conectar com SQL
conn = sqlite3.connect(":memory:")
df_vendas.to_sql("vendas", conn, index=False, if_exists="replace")

# Filtrar e exibir as vendas da categoria "Eletrônicos".
filtra_produto_eletronicos = pd.read_sql_query("SELECT * FROM vendas WHERE categoria = 'Eletrônicos'", conn)
filtra_produto_eletronicos

# Identificar e exibir o produto mais vendido (em quantidade).
produto_mais_vendido = pd.read_sql_query("""
SELECT produto, categoria, SUM(quantidade) AS total_vendido
FROM vendas
GROUP BY produto
ORDER BY total_vendido
DESC LIMIT 1""", conn)
produto_mais_vendido

# Descobrir e exibir a região com maior valor de compras.
regiao_maior_receita = pd.read_sql_query("""
SELECT regiao, SUM(receita) AS total_receita
FROM vendas
GROUP BY regiao
ORDER BY total_receita DESC
LIMIT 1
""", conn)
regiao_maior_receita

"""## Desafio extra"""

# Gráfico de barras mostrando a receita por categoria.
receita_categoria = df_vendas.groupby("categoria")["receita"].sum()

receita_categoria.plot(kind="bar")
plt.title("Receita por Categoria")
plt.xlabel("Categoria")
plt.ylabel("Receita")
plt.xticks(rotation=45)
plt.show()

# Gráfico de linha mostrando a evolução das vendas por mês.
df_vendas["data"] = pd.to_datetime(df_vendas["data"])

vendas_mes = df_vendas.groupby(
    df_vendas["data"].dt.to_period("M")
)["receita"].sum()

vendas_mes.plot(kind="line")
plt.title("Evolução das Vendas por Mês")
plt.xlabel("Mês")
plt.ylabel("Receita")
plt.show()

# Montar uma tabela dinâmica com receita por região × categoria.
tabela_dinamica = pd.pivot_table(
    df_vendas,
    values="receita",
    index="regiao",
    columns="categoria",
    aggfunc="sum"
)

tabela_dinamica

# Criar um relatório exportado em .xlsx ou .pdf.
tabela_dinamica.to_excel("relatorio_vendas.xlsx")