# -*- coding: utf-8 -*-
"""Insights na TechGrow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F8AHyaC_RJPHs4qDIZuJI4GEN1QnRrPZ

# Bibliotecas
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, ConfusionMatrixDisplay, roc_curve

"""# Coleta de Dados"""

df = pd.read_csv("Caso_Pratico_base_churn_saas.csv")

"""## Observação Inicial"""

df.head()

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

"""*   42% de churn (valor muito alto)

1. Tempo de contrato (clientes novos tendem a cancelar mais)
2. Logins (menos logins mensais tendem a gerar churn)
3. Tickets suporte (muitos tickets podem indicar problemas e podem gerar insatisfação que pode gerar churn)
4. Uso diário (baixo uso diário pode levar a churn)

### gráficos comparativos
"""

sns.boxplot(x='churn', y='tempo_contrato_meses', data=df)
plt.show()
# menos meses de contrato, mais churn

sns.boxplot(x='churn', y='logins_mes', data=df)
plt.show()
#menos logins por més, mais churn

sns.boxplot(x='churn', y='uso_media_diaria_horas', data=df)
plt.show()
# menos uso médio diário de horas, mais churn

sns.boxplot(x='churn', y='tickets_suporte', data=df)
plt.show()
#mais tickets de suporte, mais churn

"""# 2. Trate e prepare os dados"""

# Remover id_cliente
df_model = df.drop('id_cliente', axis=1)

# Aplicando One-Hot Encoding
df_model = pd.get_dummies(df_model, columns=['plano', 'regiao'], drop_first=True)
colunas_bool = df_model.select_dtypes(include='bool').columns
df_model[colunas_bool] = df_model[colunas_bool].astype(int)
df_model.head()

"""As variáveis categóricas foram transformadas utilizando One-Hot Encoding, permitindo sua utilização em modelos de machine learning. Foi utilizado o parâmetro drop_first=True para evitar multicolinearidade."""

# Normalizar Colunas
colunas_para_normalizar = [
    'tempo_contrato_meses',
    'logins_mes',
    'tickets_suporte',
    'valor_mensal',
    'qtd_funcionarios',
    'uso_media_diaria_horas'
]
scaler = StandardScaler()
df_normal = df_model.copy()
df_normal[colunas_para_normalizar] = scaler.fit_transform(df_normal[colunas_para_normalizar])
df_normal.head()

"""As variáveis numéricas foram padronizadas utilizando StandardScaler, devido à diferença de escala entre elas. Essa etapa é importante para algoritmos de machine learning sensíveis à magnitude dos dados."""

# Verifique correlações relevantes e elimine colunas redundantes.
plt.figure(figsize=(12,8))
sns.heatmap(df_normal.corr(), annot=True, cmap='coolwarm')
plt.title('Correlação após tratamento dos dados')
plt.show()

df_sem_redundancia = df_normal.drop(['uso_media_diaria_horas', 'qtd_funcionarios'], axis=1)

"""A análise de correlação identificou alta multicolinearidade entre algumas variáveis:

- `logins_mes` e `uso_media_diaria_horas` (0.99)
- `valor_mensal` e `qtd_funcionarios` (0.96)

Para evitar redundância, vou remover:

- `uso_media_diaria_horas`, mantendo logins_mes` por maior interpretabilidade
- `qtd_funcionarios`, mantendo `valor_mensal` por maior relevância para o negócio

# 3. Separe os dados em treino e teste
"""

# Utilize 70% para treino e 30% para teste.
# Defina churn como variável-alvo (target).

X = df_sem_redundancia.drop('churn', axis=1)
y = df_sem_redundancia['churn']

stratify=y

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

print(y_train.value_counts(normalize=True))
print(y_test.value_counts(normalize=True))

"""Os dados foram divididos em conjuntos de treino (70%) e teste (30%) utilizando a função train_test_split. Foi utilizado o parâmetro stratify para manter a proporção da variável alvo (churn) em ambos os conjuntos, evitando viés na modelagem.

# 4. Treine os modelos

### Regreção Logistica
"""

modelo_lr = LogisticRegression()
modelo_lr.fit(X_train, y_train)
y_pred_lr = modelo_lr.predict(X_test)

"""### Random Forest"""

modelo_rf = RandomForestClassifier(random_state=42)
modelo_rf.fit(X_train, y_train)
y_pred_rf = modelo_rf.predict(X_test)

"""### XGBoost"""

modelo_xgb = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)
modelo_xgb.fit(X_train, y_train)
y_pred_xgb = modelo_xgb.predict(X_test)

"""# 5 Avalie os resultados

### métricas de classificação
"""

def avaliar_modelo(nome, modelo, X_test, y_test):
    y_pred = modelo.predict(X_test)
    y_proba = modelo.predict_proba(X_test)[:, 1]  # probabilidade de churn

    print(f'--- {nome} ---')
    print('Accuracy:', accuracy_score(y_test, y_pred))
    print('Precision:', precision_score(y_test, y_pred))
    print('Recall:', recall_score(y_test, y_pred))
    print('F1-score:', f1_score(y_test, y_pred))
    print('ROC-AUC:', roc_auc_score(y_test, y_proba))
    print()

avaliar_modelo("Logistic Regression", modelo_lr, X_test, y_test)
avaliar_modelo("Random Forest", modelo_rf, X_test, y_test)
avaliar_modelo("XGBoost", modelo_xgb, X_test, y_test)

"""Todos os modelos apresentaram alto desempenho, com destaque para o recall igual a 1.0, indicando que todos foram capazes de identificar corretamente os clientes com churn.

Apesar do Random Forest apresentar métricas perfeitas, há indícios de overfitting devido ao tamanho reduzido da base de dados.

### matriz de confusão - Logistic Regression
"""

y_pred = modelo_lr.predict(X_test)

cm = confusion_matrix(y_test, y_pred)

disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()
plt.title("Matriz de Confusão - Logistic Regression")
plt.show()

"""O modelo previu 15 clientes como churn, sendo que 13 realmente cancelaram e 2 foram falsos positivos. Além disso, todos os clientes que não foram classificados como churn realmente permaneceram ativos.

### curva ROC
"""

y_proba = modelo_lr.predict_proba(X_test)[:, 1]

fpr, tpr, thresholds = roc_curve(y_test, y_proba)

plt.plot(fpr, tpr)
plt.plot([0,1], [0,1], linestyle='--')  # linha aleatória
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Curva ROC - Logistic Regression')
plt.show()

"""# 6 Interprete e apresente os resultados

A análise identificou que altos volumes de tickets de suporte e inadimplência são os principais fatores associados ao churn, indicando problemas de experiência e barreiras financeiras.

Além disso, baixo engajamento (logins reduzidos) sugere que parte dos clientes pode não estar extraindo valor do produto, possivelmente por desalinhamento com suas necessidades ou falhas no onboarding.

Observou-se também que clientes com maior tempo de contrato apresentam menor propensão ao churn, indicando que os primeiros meses são críticos para retenção.

Com base nesses insights, recomenda-se:

- Melhorar a experiência do usuário, reduzindo a necessidade de suporte por meio da identificação e correção de problemas recorrentes
Implementar estratégias para reduzir inadimplência, como alertas e flexibilização de pagamento
- Avaliar a adequação do produto ao público-alvo e melhorar o onboarding para aumentar o engajamento
- Focar na retenção nos primeiros meses, com acompanhamento ativo e validação de valor
- Criar incentivos de longo prazo, como benefícios por tempo de uso e estratégias de upgrade de plano
"""