# -*- coding: utf-8 -*-
"""Analise de Delivery de Refeicoes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kp1xetZNd0PFlUruDn7WB6cwrQ0v3baq

# 1. Importações
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""# 2. Carregamento dos Dados"""

df_pedidos = pd.read_csv('/content/pedidos.csv')

"""# 3. EDA"""

df_pedidos.head()

df_pedidos.tail()

df_pedidos.info()

df_pedidos.describe()

"""* Foram identificados valores nulos nas colunas `Quantidade` (19 registros) e `Preco_Unitario` (20 registros).
- A coluna `Data` está no tipo `object`.

# 4. Feature Engineering
"""

df_pedidos['Receita_Item'] = df_pedidos['Quantidade'] * df_pedidos['Preco_Unitario']
df_pedidos.head()

"""- Foi criada a coluna `Receita_Item` a partir da multiplicação de `Quantidade` e `Preco_Unitario`.

# 5. Tratamento de Dados
"""

# Identificar nulos
df_pedidos.isna().sum()

# Preencher Quantidade com a média
df_pedidos_preenchido = df_pedidos.copy()
media_qtd = df_pedidos_preenchido['Quantidade'].mean()
df_pedidos_preenchido['Quantidade'] = df_pedidos_preenchido['Quantidade'].fillna(media_qtd)

# Remover nulos de Preco_Unitario
df_pedidos_limpo = df_pedidos_preenchido.dropna(subset=['Preco_Unitario'])

# Corrigindo valores de 'Receita_Item'
df_pedidos_limpo['Receita_Item'] = (df_pedidos_limpo['Quantidade'] * df_pedidos_limpo['Preco_Unitario'])

df_pedidos_limpo.info()

df_pedidos_limpo.isna().sum()

"""* A coluna `Receita_Item` apresentou 38 valores nulos, por causa dos dados ausentes em `Quantidade` e `Preco_Unitario`.

* Os valores nulos em `Quantidade` foram preenchidos com a média da coluna

* As linhas com valores nulos em `Preco_Unitario` foram removidas

* A coluna `Receita_Item` foi recalculada para garantir que não haja mais valores nulos.

# 6. Agregações
"""

# Análise por item
pedidos_por_itens = df_pedidos_limpo.groupby('Item').agg(
    Quantidade_Total = ('Quantidade', 'sum'),
    Receita_Total = ('Receita_Item', 'sum')
).reset_index()
print(pedidos_por_itens)

itens_mais_pedidos = pedidos_por_itens.sort_values(by='Quantidade_Total', ascending=False).iloc[0:5]
print(itens_mais_pedidos)

itens_maior_receita = pedidos_por_itens.sort_values(by='Receita_Total', ascending=False).iloc[0:5]
print(itens_maior_receita)

"""* O item mais vendido foi `Hamburguer`, com um total de 510.805104 unidades vendidas.

* O item com maior geração de receita foi `Pizza Calabresa`, com 15903.647958 em receita total.

* O item mais vendido e o 4º com maior receita, enquanto o com maior receita não está nos 5 mais vendidos. Indicando diferenças de preço entre os produtos.

# 7. Análise Temporal
"""

# Análise por período
df_pedidos_limpo['Data'] = pd.to_datetime(df_pedidos_limpo['Data'])
df_pedidos_limpo.info()

df_pedidos_limpo['Mes_Pedido'] = df_pedidos_limpo['Data'].dt.month
df_pedidos_limpo.head()

pedidos_por_mes = df_pedidos_limpo.groupby('Mes_Pedido')['Receita_Item'].sum().reset_index()
print(pedidos_por_mes)

# gráfico
plt.plot(pedidos_por_mes['Mes_Pedido'], pedidos_por_mes['Receita_Item'])
plt.title('Receita por Mês')
plt.xlabel('Mês')
plt.ylabel('Receita')
plt.show()

"""* A receita apresenta variações ao longo dos meses, sem um crescimento contínuo.

* Um pico de vendas nos meses 2 e 9.

* Há uma queda no mês 3 e uma outra muito maior no mês 10, seguida de leve recuperação.

# 8. Merge
"""

df_cardapio = pd.read_csv('/content/cardapio.csv')

# Integre com cardápio
df_merge = pd.merge(df_pedidos_limpo, df_cardapio, on='Item', how='left')
df_merge.head()

receita_por_categoria = df_merge.groupby('Categoria').agg(Receita_Total = ('Receita_Item', 'sum')).reset_index()
print(receita_por_categoria)

categoria_maior_receita = receita_por_categoria.sort_values(by='Receita_Total', ascending=False).iloc[0]
categoria_maior_receita.head()

"""* A categoria com maior geração de receita foi `Salgados`.

# 9. Filtros
"""

# Aplique filtros específicos
df_query = df_merge.query('Categoria == "Salgados" and Quantidade > 10')
print(df_query)

"""# 10. KPIs"""

# Calcule indicadores
receita_total_gerada = df_merge['Receita_Item'].sum()
print(receita_total_gerada)

total_itens_vendidos = df_merge['Quantidade'].sum()
print(total_itens_vendidos)

total_pedidos = df_merge['ID_Pedido'].nunique()

ticket_medio = receita_total_gerada / total_pedidos
print(ticket_medio)

"""- Receita Total: 122652.59153132251

- Total de Itens Vendidos: 6833.245939675175

- Ticket Médio: 285.23858495656395

# 11. Desafio Extra
"""

percentis_preco = np.percentile(df_merge['Preco_Unitario'], [25, 50, 75])
print(percentis_preco)

percentis_quantidade = np.percentile(df_merge['Quantidade'], [25, 50, 75])
print(percentis_quantidade)