# -*- coding: utf-8 -*-
"""Lista de Compras Rocketseat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vMbd_0m1KlwTE4m9kdg5Qp1-CrVCfD1V
"""

itens = []

def main():
  print('Bem-vindo à lista de compras!')
  while True:
    print("\nMenu:")
    print("1. Adicionar item")
    print("2. Listar itens")
    print("3. Marcar item como comprado")
    print("4. Remover item")
    print("5. Mudar a quantidade de um item")
    print("6. Listar itens não comprados")
    print("7. Sair")
    opc = input("Escolha: ")

    if opc == '1':
      item = input('Digite um item que você deseja adicionar: ')
      while not item.strip():
        item = input('Por favor, digite um item: ')
      while True:
        try:
          quantidade = int(input(f'Digite a quantidade de {item}: '))
          if quantidade <= 0:
            print('A quantidade deve ser maior que zero.')
            continue
          break
        except ValueError:
          print('Por favor, digite um número válido.')
      adicionar_item(item, quantidade)

    elif opc == '2':
      listar_itens()

    elif opc == '3':
      listar_itens()
      try:
        indice = int(input('Digite o número do item que você deseja marcar como comprado: ')) - 1
        marcar_comprado(indice)
      except ValueError:
        print('Entrada inválida! Por favor digite um número!')

    elif opc == '4':
      listar_itens()
      try:
        indice = int(input('Digite o número do item que você deseja remover: ')) - 1
        remover_item(indice)
      except ValueError:
        print('Entrada inválida! Por favor digite um número! ')

    elif opc == '5':
      listar_itens()
      try:
        indice = int(input('Digite o número do item que você deseja mudar a quantidade: ')) - 1
        mudar_quantidade(indice)
      except ValueError:
        print('Entrada inválida! Por favor digite um número! ')

    elif opc == '6':
      lista_nao_comprados()

    elif opc == '7':
      print("Até as próximas compras!")
      break
    else:
      print('Por favor, coloque um número entre 1 e 7.')

def adicionar_item(item, quantidade):
  print(f'Você adicionou {quantidade} de {item}')
  itens.append({'Item': item, 'Quantidade': quantidade, 'Comprado': False})

def listar_itens():
  if not itens:
    print('Nenhum item encontrado.')
    return
  print('\nLista de Itens: ')
  for i, item in enumerate(itens):
    comprado = '[X]' if item['Comprado'] else '[ ]'
    print(f'{i+1}. {comprado} - {item["Quantidade"]} {item["Item"]}')

def marcar_comprado(indice):
    if 0 <= indice < len(itens):
      itens[indice]['Comprado'] = True
      print(f'item {itens[indice]["Item"]} foi comprado')
    else:
      print('Índice de item inválido!')

def mudar_quantidade(indice):
  if 0 <= indice < len(itens):
    print(f'Você selecionou {itens[indice]["Item"]} que tem {itens[indice]["Quantidade"]}')
    while True:
      try:
        nova_quantidade = int(input(f'Digite a nova quantidade de {itens[indice]["Item"]}: '))
        if nova_quantidade <= 0:
          print('A quantidade deve ser maior que zero.')
          continue
        break
      except ValueError:
        print('Por favor, digite um número válido.')
    itens[indice]['Quantidade'] = nova_quantidade

def lista_nao_comprados():
  if not itens:
    print('Nenhum item encontrado.')
    return
  print('\nLista de itens não comprados: ')
  for i, item in enumerate(itens):
    if  not item['Comprado']:
      print(f'{i+1}. {item["Quantidade"]} {item["Item"]}')

def remover_item(indice):
  if 0 <= indice < len(itens):
    item = itens.pop(indice)['Item']
    print(f'"{item}" foi removida com sucesso!')
  else:
    print('Índice do Item inválido!')

main()