# -*- coding: utf-8 -*-
"""Mini_Projeto_Analise_De_Vendas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12oGMRsh54AZzvMVOPDfOq7FTwClUj4h3
"""

import pandas as pd
import numpy as np

#Primeiras linhas
df_vendas = pd.read_csv('/content/vendas.csv')

df_vendas.head()

#Últimas linhas
df_vendas.tail()

#Verificando informações gerais do DF
df_vendas.info()

df_vendas.describe()

#Criar uma coluna chamada Receita Total (Quantidade * Preco_unitário)
df_vendas['Receita_Total'] = df_vendas['Quantidade'] * df_vendas['Preco_Unitario']
df_vendas.head()

#Selecionar apenas as colunas Produto e Receita Total
df_vendas[['Produto', 'Receita_Total']].head()

#Linhas onde a quantidade é maior que 20
df_vendas[df_vendas['Quantidade'] > 20].head()

#loc (selecionar linhas e colunas por rótulo (Produto = 'Monitor'))
df_vendas.loc[df_vendas['Produto'] == "Monitor", ['ID_Venda', 'Quantidade', 'Preco_Unitario']].head()

#Selecionar as primeiras 3 linhas e as colunas de 1 a 3
df_vendas.iloc[0:3, 1:4]

#Cálculos (Pandas e Numpy)"
#Descobrir o faturamento (Receita Total)
print(f'Receita Total de Vendas da Loja: {df_vendas['Receita_Total'].sum():.2f}')

#Preço médio unitário dos produtos
print(f'O preço médio unitário dos produtos é: {df_vendas['Preco_Unitario'].mean():.2f}')

#Quantidade mínima e máxima de produtos vendidos
print(f'Quantidade mínima de produtos vendidos: {df_vendas['Quantidade'].min()}')
print(f'Quantidade máximo de produtos vendidos: {df_vendas['Quantidade'].max()}')

#Simular valores ausentes dentro do DF
df_vendas_com_nan = df_vendas.copy()
df_vendas_com_nan.loc[df_vendas_com_nan.sample(frac=0.05).index, 'Preco_Unitario'] = np.nan
df_vendas_com_nan.loc[df_vendas_com_nan.sample(frac=0.03).index, 'Quantidade'] = np.nan

# Verificar se existe valores ausentes
#df_vendas_com_nan.info()
df_vendas_com_nan.isna().sum()

# Preencher com a média os valores nulos da coluna Quantidade (fillna)
df_vendas_preenchido = df_vendas_com_nan.copy()
media_qtd = df_vendas_preenchido['Quantidade'].mean()
df_vendas_preenchido['Quantidade'].fillna(media_qtd, inplace=True)

df_vendas_preenchido.info()

#Remover os valores ausentes encontrados em Preço Unitário
df_vendas_limpo = df_vendas_preenchido.dropna(subset=['Preco_Unitario'])

df_vendas_limpo.info()

#Agrupar por produtos e calcular quantidade e receita total
vendas_por_produto = df_vendas_limpo.groupby('Produto').agg(
    Quantidade_Total = ('Quantidade', 'sum'),
    Receita_Total = ('Receita_Total', 'sum')
).reset_index()
print(vendas_por_produto)

#Ordenar os valores por quantidade total para saber o produto mais vendido
produto_mais_vendido = vendas_por_produto.sort_values(by='Quantidade_Total', ascending=False).iloc[0]
print(produto_mais_vendido)

# Ordenar os valores por receita total para saber o maior valor total gerado
produto_maior_receita = vendas_por_produto.sort_values(by='Receita_Total', ascending=False).iloc[0]
print(produto_maior_receita)

df_produtos = pd.read_csv('/content/produtos.csv')
df_produtos.info()

df_produtos.head()

#Converter a coluna Data_Venda para o tipo correto de data
df_vendas_limpo['Data_Venda'] = pd.to_datetime(df_vendas_limpo['Data_Venda'])

df_vendas_limpo.info()

#Analisar as vendas por mês
df_vendas_limpo['Mes_Venda'] = df_vendas_limpo['Data_Venda'].dt.month

df_vendas_limpo.head()

#Agrupar por mês para calcular a receita total mês a mês
vendas_por_mes = df_vendas_limpo.groupby('Mes_Venda')['Receita_Total'].sum().reset_index()
print(vendas_por_mes)

#Combinar os Dados de vendas e produtos
df_merge = pd.merge(df_vendas, df_produtos, on='Produto', how='left')
print(df_merge)

#Análise de vendas por categoria (Receita Total por categoria)
vendas_por_categoria = df_merge.groupby('Categoria')['Receita_Total'].sum().reset_index()
print(vendas_por_categoria)

#Filtragem dentro do DataFrame
# Filtrar por coluna (Produto, Quantidade, Receita_Total)
df_colunas_filtradas = df_merge.filter(items=['Produto', 'Quantidade', 'Receita_Total'])
print(df_colunas_filtradas)

#Filtragem mais avançadas (Produto Teclado, quantidade > 10)
df_query = df_merge.query('Produto == "Teclado" and Quantidade > 10')
print(df_query)